---
- name: Install NGINX last version
  become_method: 
    sudo
  yum: 
    name: nginx 
    state: latest
  notify:
    - Restart nginx
    - Enable nginx

- name: Create directory site enabled 
  file: 
    path: /etc/nginx/sites-available
    state: directory
