---
##########################################################
############   Add repository MariaDB v.X.X.  ############
##########################################################
- name: Add official MariaDB repository
  yum_repository:
    name: MariaDB
    description: Official MariaDB repository
    baseurl: "http://{{ mariadb_mirror }}/{{ mariadb_version }}/{{ ansible_distribution|lower|regex_replace('redhat', 'rhel')|regex_replace('oraclelinux', 'centos') }}{{ ansible_distribution_major_version }}-amd64"
    gpgkey: https://yum.mariadb.org/RPM-GPG-KEY-MariaDB
    gpgcheck: true
  tags: mariadb
##########################################################
############   Install MariaDB v.X.X.         ############
##########################################################
- name: Install packages
  package:
    name: "{{ mariadb_packages }}"
    state: installed
  tags: mariadb
